[media-user]
version = 1.0.0.a1
url = https://api.github.com/repos/technology-vision-zurikato/media-user/releases/latest
path = /home/zurikato
dependencies = ''
size = 3894

[admin-user]
version = 1.0.0.a3
path = /home/zurikato
dependencies = ''
url = https://api.github.com/repos/technology-vision-zurikato/admin-user/releases/latest
size = 4216682

[api-device]
version = 1.0.0.a3
path = /home/zurikato
dependencies = ''
url = https://api.github.com/repos/technology-vision-zurikato/api-device/releases/latest
size = 4216682

[ad-push-device]
version = 1.0.0.a3
path = /home/zurikato
dependencies = ''
url = https://api.github.com/repos/technology-vision-zurikato/ad-push-device/releases/latest
size = 4216682
