[media-user]
version = 1.0.0.a1
url = https://raw.github.com/siewdass/siewdass.github.io/master/media-user.zip
path = /home/zurikato
dependencies = ''
size = 4086


[ad-push-device]
version = 1.0.0.a3
path = /home/zurikato
dependencies = ''
url = https://raw.github.com/siewdass/siewdass.github.io/master/adserver-1.0.0.zip
size = 4216682
