[media-user]
version = 1.0.0.a1
url = https://github.com/siewdass/siewdass.github.io/archive/v1.2.6.zip
path = '/home/siewdass/media-user/siewdass.github.io-1.2.6
dependencies = ''
size = 4086


[AD-PUSH-DEVICE]
version = 1.0.0.a3
path = '/home/siewdass/media-user
dependencies = ''
url = https://github.com/siewdass/siewdass.github.io/archive/v1.2.6.zip
size = 1908
